apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-app-deployment
  labels:
    app: kafka-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-app
      type: deployment
  template:
    metadata:
      labels:
        app: kafka-app
        type: deployment
    spec:
      containers:
      - name: kafka-app
        image: kafka-app:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: POD_NUMBER
          value: "67"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "localhost:9092"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
