apiVersion: v1
kind: Service
metadata:
  name: kafka-service-deployment
  labels:
    app: kafka-app
spec:
  type: ClusterIP
  selector:
    app: kafka-app
    type: deployment
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  sessionAffinity: None
